# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: test
  displayName: 'Building and Testing'
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04
      MacOS:
        vmImage: macOS-10.13
  pool:
    vmImage: $(vmImage)

  steps:
  - script: ./.ci/install.sh
    displayName: 'Setup on POSIX!'

  - script: ./.ci/script.sh
    displayName: 'Testing on POSIX!'
